---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 9:07 PM
---



local cjson = require('cjson')
ngx.req.read_body()
local post_body = ngx.req.get_body_data()
local post_params = cjson.decode(post_body)
local ad_count = post_params.ad_counts
if ad_count == nil then
    ad_count = 3
else
    ad_count = tonumber(ad_count) *2
end
local service_name=post_params.service_name
local ads = {}
while ad_count >= 1 do
    ad_count = ad_count -1
    table.insert(ads,
        {
            recommend="广告",
         id= "sfst_ad_id_"..tostring(ad_count),
         service=service_name,
         adtype= 8, position=ad_count,
         type= "ad",
         product="sfst",
         bid_price= tonumber(math.random()*10), ad_version='1', bid_version='v3',
            monitor_url="第三方监控链接",
            value= {
                bid_value=math.random(),
                bid_wt = math.random(),

            },
            channel='sfst'

    })
end

ngx.print(cjson.encode(ads))
ngx.eof()
