---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 5:11 PM
---

-- 工具类 校验各种变量是否合法


local _M = { version = "0.0.1" }


-- 判断s的类型是否为`string`
-- @param any s
-- @param is_care_empty bool, 是否关心s为空字符串，
--        若关心，且s为空字符串，则返回false。
-- @return true or fasle
function _M.is_string(s, is_care_empty)
    is_care_empty = is_care_empty or false
    if s == nil or type(s) ~= "string" then
        return false
    end
    if is_care_empty and string.len(s) == 0 then
        return false
    end
    return true
end

-- 判断s是否为非空字符串
-- @param any s
-- @return true or fasle
function _M.is_non_empty_string(s)
    return _M.is_string(s, true)
end

-- 判断tb的类型是否为`table`
-- @param any tb,
-- @param is_care_empty bool, 是否关心tb为空，
--        若关心，且s为空，则认为s不是字符串
-- @return true or fasle
function _M.is_table(tb, is_care_empty)
    is_care_empty = is_care_empty or false
    if tb == nil or type(tb) ~= "table" then
        return false
    end
    if is_care_empty and next(tb) == nil then
        return false
    end
    return true
end

-- 判断s是否为非空table
-- @param any s
-- @return true or fasle
function _M.is_non_empty_table(tb)
    return _M.is_table(tb, true)
end

-- 判断s是否为非number
-- @param any s
-- @return true or fasle
function _M.is_number(n)
    if n == nil or type(n) ~= "number" then
        return false
    end
    return true
end


-- 判断两个array(table)的值是否相等
-- @params any tb
-- @return true or false
function _M.is_equal_array(a, b)
    if a == nil or b == nil then
        return false
    end
    if type(a) ~= "table" or type(a) ~= "table" then
        return false
    end
    if a == b then
        return true
    end

    local a_len = #a
    local b_len = #b
    if a_len ~= b_len then
        return false
    end

    for i in ipairs(a) do
        if a[i] ~= b[i] then
            return false
        end
    end

    return true
end

-- 判断两个dict(table)的值是否相等
-- @params any a,b  目前仅支持一级dict
-- @return true or false
function _M.is_equal_dict(a, b)
    if a == nil or b == nil then
        return false
    end
    if type(a) ~= "table" or type(a) ~= "table" then
        return false
    end
    if a == b then
        return true
    end

    for k,v in ipairs(a) do
        if v ~= b[k] then
            return false
        end
    end

    return true
end

return _M
