---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/7 5:29 PM
---


module(..., package.seeall)
function new(self, core)
    return setmetatable({core = core}, {__index=self})
end

function render(self)
    local ads= {}
    local modules = self.core.scheduler.modules
    if modules then
        for _, mo in ipairs(modules) do
            if mo.data then
                if mo.data.data then
                    ads = mo.data.data
                else
                    ads = mo.data
                end
                for _, _data in ipairs(ads) do
                    _data.ad_render= {_data.id..'的广告物料填充'}
                end

            end
        end

    end
end

