---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/7 5:28 PM
---

module(..., package.seeall)

function run(core)
    local c = core.service_conf.render
    if c then
        local t = require(c)
        local _render = t:new(core)
        _render:render()

    end
end