---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 11:41 AM
---

module(..., package.seeall)
-- nginx 配置的全局变量
-- 暂停使用，同时需保留

redis_pool= {
    ['local'] = {
        { ['host'] = '127.0.0.1', ['port'] = 6379 },
    },
    ['remote'] = {
        { ['host'] = '39.106.126.216', ['port'] = 6379 },
    }
}

