---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 5:12 PM
---

local IUtils = require('lib.itypes')
local _M = { _VERSION = "0.0.1" }
local utils = require('lib.utils')
local cjson = require('cjson')

-- 判断当前访客uid是否在全局黑名单中
-- @uid string 当前访客uid
function _M.is_black_user(self, uid)
    if not IUtils.is_non_empty_string(uid) then
        return false
    end

    -- 查询是否命中全局黑名单
    if self:is_in_black_list_uid(uid) then
        return true
    end
    return false
end

function _M.is_in_black_list_uid(self, uid)
    if type(uid) ~='string'  then
        return false
    end
    local redis = require('service.redis')
    local const = require('config.redis')
    local black_list =redis.getByKey('global_blacklist',const.redis_env) -- '[1,2,3,4]'
    local status , tb_bl = pcall(cjson.decode,black_list)
    if status then
        if  utils.in_table(uid,tb_bl) then
            return true
        end

    end

    return false

end



return _M
