---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 7:22 PM
---

-- IDX竞价模型
--
--  Note: 本模块及其子模块[能且仅能]修改cands[i].inter内的数据，对其他数据结构不得做修改。


local DefaultBidModelV2 = require("ad_idx.idx_bid_module.bid_module")
local DefaultBidModelV1 = require("ad_idx.idx_bid_module.bid_module_v1")
local _M = { _VERSION = "0.0.1"}

local BID_MODELS = {
    v2 = DefaultBidModelV2,
    V1 = DefaultBidModelV1
}

function _M:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    return o
end

-- 获取竞价模型
-- 依据请求参数决定使用何种竞价模型
function _M:match_model()
    local model = BID_MODELS[self.model_version]
    return model
end

-- 竞价
-- @return cand table 返回竞价成功的候选,无候选则返回nil
function _M:bid()
    if next(self.cands) == nil then
        ngx.log(ngx.ERR, "cands is empty")
        return nil
    end

    -- 若只有一个候选，则不需要竞价，更新竞价状态后直接返回，提升效率
    if #self.cands == 1 then
        local cand = self.cands[1]
        cand.status = 'success'
        return cand
    end

    --  获取竞价模型
    local model = self:match_model()
    --  竞价计算
    local win = model.bid(self.cands)
    if win == nil then
        ngx.log(ngx.ERR, string.format("%s bid failed", model.name))
        return nil
    end


    return win
end


return _M
