---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 5:38 PM
---
local _M = {_VERSION = "0.0.1"}
function _M.get_user_identifier_info(self,uid)


end

return _M