---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 5:38 PM
---
local _M = { _VERSION = "0.0.1" }
local cjson = require('cjson')
-- 根据业务号获取策略,一版情况用户画像都存储在redis里面
function _M.get_strategy_info(self, business)
    if type(business) ~= 'string' then
        return { strategy = '策略信息' }
    end
    local redis = require('service.redis')
    local const = require('config.redis')
    local business_stra = redis.getByKey(business, const.redis_env)
    if type(business_stra) == 'table' then
        return cjson.decode(business_stra)
    end
    return { strategy = '策略信息' }

end

return _M