---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 7:23 PM
---




local _M = { _VERSION = "0.0.1"}

_M.name = "idx_bid_model_v1"


-- 计算最优广告
-- @parma table cands
-- @return table 返回候选集中竞价最优的广告，无候选则返回nil
function _M.bid(cands,ad_counts)
    if type(cands)~='table' or next(cands) == nil then
        return nil
    end
    local function bid_price_comp(bid_ad1,bid_ad2)
        return bid_ad1.bid_price > bid_ad2.bid_price
    end
    table.sort(cands,bid_price_comp)
    return cands
end

return _M



