---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 1:29 PM
---
-----------------------------------------------------------------------------
-- ./sm文件夹里面各service module文件的公共父类
--
-----------------------------------------------------------------------------

module(..., package.seeall)

-----------------------------------------------------------------------------
-- 执行方法，处理capture调用返回的数据，并将其存放在data变量中
-- Input
-- @param self 调用者自身self
-- @param resp capture调用返回的数据
-- Returns
-- @return
-----------------------------------------------------------------------------
function run(self, resp)

    if resp.status == 200 then
        local cjson = require('cjson')
        local f, _data = pcall(cjson.decode, resp.body)
        if f and _data ~= cjson.null then
            self.data = _data
        end
    end
end

