---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/7/6 1:22 PM
---

local ultimate_degrade = tonumber(os.getenv('UVE_ULTIMATE_DEGRADE'))
if ultimate_degrade and ngx.var.uve_service_name and ngx.var.uve_service_name == 'main_feed' then
    local rand = math.random(1, 1000)
    if ultimate_degrade >= rand then
        ngx.say('{"errno":9001,"error":"204: give up traffic, current ultimate degrade: ' .. ultimate_degrade .. ' >= rand:' .. rand .. '"}')
        ngx.exit(ngx.HTTP_OK)
    end
end
local core_t = require 'ads.core'
local core = core_t:new()
core:run()

