---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 1:25 PM
---
--local core_t = require('ad_idx.core')
--local core = core_t:new()
--local req_body={is_debug=true}
--local uve = {uid='10001',from='android',ad_counts=10,strategy_products={'sfst','wax'},ad_show=true}
--core:run(req_body,uve)
local redis = require('service.redis')
local const = require('config.redis')
local resp,err=redis.getAllByKeyNew('ad_online_brand',const.redis_env)

local cjson =require('cjson')
for k, v in pairs(resp) do
    if k%2 == 0 then
        ngx.print(type(cjson.decode(v)))
    end

end