---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 1:25 PM
---
local core_t = require('ad_idx.core')
local core = core_t:new()
local req_body={is_debug=true}
local uve = {uid='u0001',from='android',ad_counts=1,strategy_products={'sfst','wax'},ad_show=false}
core:run(req_body,uve)
